# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 00:06
from __future__ import unicode_literals

import corpus.fields.slug
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', corpus.fields.slug.SlugField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'corpora',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField()),
                ('plain_text', models.TextField()),
                ('title', models.TextField()),
                ('author', models.TextField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.Corpus')),
            ],
        ),
    ]
