# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='identifier',
            field=models.CharField(db_index=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='text',
            unique_together=set([('corpus', 'identifier')]),
        ),
    ]
