# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_add_identifier_to_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='author',
            new_name='author_full',
        ),
    ]
