# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0003_rename_author_to_author_full'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='author_full',
            new_name='author_name_full',
        ),
        migrations.AddField(
            model_name='text',
            name='author_name_first',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='author_name_last',
            field=models.TextField(null=True),
        ),
    ]
