# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 22:42
from __future__ import unicode_literals

import corpus.fields.metadata
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0005_make_plain_text_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='author_name_first',
            field=corpus.fields.metadata.MetadataField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='author_name_full',
            field=corpus.fields.metadata.MetadataField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='author_name_last',
            field=corpus.fields.metadata.MetadataField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='plain_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='source_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
