# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0006_make_source_text_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='source_text',
        ),
        migrations.AlterField(
            model_name='text',
            name='plain_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
