# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpora', '0002_auto_20160304_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='bibliographicCitation',
            new_name='bibliographic_citation',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='dateAccepted',
            new_name='date_accepted',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='dateCaptured',
            new_name='date_captured',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='dateCopyrighted',
            new_name='date_copyrighted',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='dateSubmitted',
            new_name='date_submitted',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='hasFormat',
            new_name='has_format',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='hasPart',
            new_name='has_part',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='isFormatOf',
            new_name='is_format_of',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='isPartOf',
            new_name='is_part_of',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='isReferencedBy',
            new_name='is_referenced_by',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='isReplacedBy',
            new_name='is_replaced_by',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='isVersionOf',
            new_name='is_version_of',
        ),
    ]
