# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpora', '0003_auto_20160307_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='plain_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='source_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
