# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 22:12
from __future__ import unicode_literals

import corpora.fields.slug
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpora', '0004_auto_20160307_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='slug',
            field=corpora.fields.slug.SlugField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
