# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpora', '0005_add_slug_to_corpus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='plain_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
