"""Add Corpus and Text.

Revision ID: 2219065cebc7
Revises:
Create Date: 2016-06-29 12:01:31.270910

"""

# revision identifiers, used by Alembic.
revision = '2219065cebc7'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corpus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corpus_id', sa.Integer(), nullable=True),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['corpus_id'], ['corpus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text')
    op.drop_table('corpus')
    ### end Alembic commands ###
