"""Remove uuid from Export.

Revision ID: 28248b1080f4
Revises: a2049a36c106
Create Date: 2016-07-26 21:12:02.541459

"""

# revision identifiers, used by Alembic.
revision = '28248b1080f4'
down_revision = 'a2049a36c106'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('export', 'uuid')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export', sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
