"""Add sample_size to Export.

Revision ID: 8ff0f77bd0bc
Revises: 3ba476a6b0dc
Create Date: 2016-07-24 22:34:48.624796

"""

# revision identifiers, used by Alembic.
revision = '8ff0f77bd0bc'
down_revision = '3ba476a6b0dc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export', sa.Column('sample_size', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('export', 'sample_size')
    ### end Alembic commands ###
