"""Remove sample_size from Export.

Revision ID: 90360b0ea91f
Revises: 28248b1080f4
Create Date: 2016-07-29 16:47:22.011974

"""

# revision identifiers, used by Alembic.
revision = '90360b0ea91f'
down_revision = '28248b1080f4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('export', 'sample_size')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export', sa.Column('sample_size', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
