"""Add uuid to Export.

Revision ID: a2049a36c106
Revises: f1cf002c3a1c
Create Date: 2016-07-25 01:55:57.002857

"""

# revision identifiers, used by Alembic.
revision = 'a2049a36c106'
down_revision = 'f1cf002c3a1c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export', sa.Column('uuid', postgresql.UUID(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('export', 'uuid')
    ### end Alembic commands ###
