"""On Text, make corpus_id and identifier unique together.

Revision ID: b8c2ab3f513a
Revises: be8f28fccf74
Create Date: 2016-06-29 14:27:42.214583

"""

# revision identifiers, used by Alembic.
revision = 'b8c2ab3f513a'
down_revision = 'be8f28fccf74'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'text', ['corpus_id', 'identifier'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'text', type_='unique')
    ### end Alembic commands ###
