"""Make corpus_id on Text required.

Revision ID: bb79aff3199e
Revises: b8c2ab3f513a
Create Date: 2016-06-29 19:00:47.611397

"""

# revision identifiers, used by Alembic.
revision = 'bb79aff3199e'
down_revision = 'b8c2ab3f513a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('text', 'corpus_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('text', 'corpus_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
