"""cascade_corpus_deletes_to_text

Revision ID: e07265289e92
Revises: f6994b159f0f
Create Date: 2016-07-21 19:35:31.458595

"""

# revision identifiers, used by Alembic.
revision = 'e07265289e92'
down_revision = 'f6994b159f0f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('text_corpus_id_fkey', 'text', type_='foreignkey')
    op.create_foreign_key(None, 'text', 'corpus', ['corpus_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'text', type_='foreignkey')
    op.create_foreign_key('text_corpus_id_fkey', 'text', 'corpus', ['corpus_id'], ['id'])
    ### end Alembic commands ###
