"""Add finished to Export.

Revision ID: f1cf002c3a1c
Revises: ffc6b2f0e330
Create Date: 2016-07-25 01:49:01.722368

"""

# revision identifiers, used by Alembic.
revision = 'f1cf002c3a1c'
down_revision = 'ffc6b2f0e330'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export', sa.Column('finished', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('export', 'finished')
    ### end Alembic commands ###
