"""Add corpora to Export.

Revision ID: ffc6b2f0e330
Revises: 8ff0f77bd0bc
Create Date: 2016-07-24 22:49:48.986456

"""

# revision identifiers, used by Alembic.
revision = 'ffc6b2f0e330'
down_revision = '8ff0f77bd0bc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export', sa.Column('corpora', postgresql.ARRAY(sa.Integer()), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('export', 'corpora')
    ### end Alembic commands ###
